# Generated by Django 3.2.8 on 2022-06-11 11:37

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categorie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Dci',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('action_therapeutique', models.CharField(max_length=250)),
                ('indications', models.CharField(max_length=50)),
                ('presentation', models.CharField(max_length=250)),
                ('posologie', models.CharField(max_length=250)),
                ('duree', models.CharField(max_length=250)),
                ('precautions', models.TextField(blank=True, null=True)),
                ('remarques', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SousCategorie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('categorie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medicament.categorie')),
            ],
        ),
        migrations.CreateModel(
            name='Medicament',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medicament_code', models.CharField(max_length=100)),
                ('nom_commercial', models.CharField(max_length=250)),
                ('dosage', models.CharField(max_length=50)),
                ('forme', models.CharField(max_length=100)),
                ('prix_unitaire', models.DecimalField(decimal_places=2, max_digits=7)),
                ('numero_lot', models.CharField(blank=True, max_length=250)),
                ('date_peremption', models.DateTimeField()),
                ('nom_fabricant', models.TextField(blank=True, null=True)),
                ('addresse_fabricant', models.TextField(blank=True, null=True)),
                ('date_added', models.DateTimeField(default=django.utils.timezone.now)),
                ('date_created', models.DateTimeField(auto_now=True)),
                ('dci', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medicament.dci')),
            ],
        ),
        migrations.AddField(
            model_name='dci',
            name='sous_categorie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medicament.souscategorie'),
        ),
    ]
