# Generated by Django 3.2.8 on 2022-06-11 13:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('medicament', '0002_auto_20220611_1211'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Conditionnement',
            new_name='Type',
        ),
        migrations.RemoveField(
            model_name='dci',
            name='conditionnement',
        ),
        migrations.AddField(
            model_name='medicament',
            name='Type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='medicament.type'),
        ),
    ]
