# Generated by Django 3.2.8 on 2022-06-11 13:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medicament', '0003_auto_20220611_1316'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Type',
            new_name='Liste',
        ),
        migrations.RenameField(
            model_name='medicament',
            old_name='Type',
            new_name='liste',
        ),
    ]
