# Generated by Django 3.2.8 on 2022-06-17 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicament', '0005_auto_20220614_1818'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicament',
            name='quantite',
            field=models.IntegerField(blank=True, max_length=20, null=True),
        ),
    ]
