# Generated by Django 3.2.8 on 2022-06-12 11:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('medicament', '0004_auto_20220611_1337'),
    ]

    operations = [
        migrations.CreateModel(
            name='Commande',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant', models.FloatField()),
                ('date_created', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('age', models.IntegerField(null=True)),
                ('sexe', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Detail_Ord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qte', models.IntegerField()),
                ('commande', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='caise.commande')),
                ('medicament', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='medicament.medicament')),
            ],
        ),
        migrations.AddField(
            model_name='commande',
            name='patient',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='caise.patient'),
        ),
    ]
